"""macOS Verified Screenshot - Capture screenshots with verification and retry logic."""

from .actions import (
    activate_window,
    capture_simple,
    capture_verified,
    capture_window_image,
    sanitize_app_name,
)
from .cli import create_parser, main
from .core import (
    compute_hash_distance,
    compute_image_hash,
    find_target_window,
    get_image_dimensions,
    is_image_blank,
    verify_basic,
    verify_content,
    verify_dimensions,
    verify_text,
)
from .models import (
    DEFAULT_HASH_THRESHOLD,
    DEFAULT_MAX_RETRIES,
    DEFAULT_RETRY_DELAY_MS,
    DEFAULT_SETTLE_MS,
    CaptureConfig,
    CaptureError,
    CaptureResult,
    MaxRetriesError,
    RetryStrategy,
    ScreenshotError,
    VerificationResult,
    VerificationStrategy,
    WindowNotFoundError,
    WindowTarget,
)

__all__ = [
    "DEFAULT_HASH_THRESHOLD",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_RETRY_DELAY_MS",
    "DEFAULT_SETTLE_MS",
    "CaptureConfig",
    "CaptureError",
    "CaptureResult",
    "MaxRetriesError",
    "RetryStrategy",
    "ScreenshotError",
    "VerificationResult",
    "VerificationStrategy",
    "WindowNotFoundError",
    "WindowTarget",
    "activate_window",
    "capture_simple",
    "capture_verified",
    "capture_window_image",
    "compute_hash_distance",
    "compute_image_hash",
    "create_parser",
    "find_target_window",
    "get_image_dimensions",
    "is_image_blank",
    "main",
    "sanitize_app_name",
    "verify_basic",
    "verify_content",
    "verify_dimensions",
    "verify_text",
]
